- name: Get ACM Arn
  shell: 'aws acm list-certificates --query 'CertificateSummaryList[].CertificateArn[] --output text'

- name: Install Harbor helm
  shell: 'helm repo add harbor https://helm.goharbor.io'

- name: Fetch Harbor version
  shell: 'helm fetch harbor/harbor --untar --version 1.11.0'

- name: Config Harbor yaml
  lineinfile:
    path: '~/harbor/values.yaml'
    regexp: "{{ item.src }}"
    line: "{{ item.dst }}"
  loops:
    - { src: '^expose.tls.certSource=.*', dst: 'expose.tls.certSource=none' }
    - { src: '^expose.ingress.hosts.core=*', dst: 'expose.ingress.hosts.core=harbor.{{ cluster_name }}' }
